apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magios_blue
      version: blue
  template:
    metadata:
      labels:
        app: magios_blue
        version: blue
    spec:
      containers:
        - name: mi-app
          image: ochito/magios-blue:1.0
          ports:
            - containerPort: 5000
