apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
      version: green
  template:
    metadata:
      labels:
        app: mi-app
        version: green
    spec:
      containers:
      - name: mi-app
        image: <DOCKERHUB_USERNAME>/mi_app:latest
        ports:
        - containerPort: 5000
