apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
      version: blue
  template:
    metadata:
      labels:
        app: mi-app
        version: blue
    spec:
      containers:
      - name: mi-app
        image: ochito/mi_app:latest
        ports:
        - containerPort: 5000
