apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi_app
      version: blue
  template:
    metadata:
      labels:
        app: mi_app
        version: blue
    spec:
      containers:
        - name: mi-app
          image: ochito/magios-blue:2.0
          ports:
            - containerPort: 5000
