apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magios_green
      version: green
  template:
    metadata:
      labels:
        app: magios_green
        version: green
    spec:
      containers:
        - name: mi-app
          image: ochito/magios-green:1.0
          ports:
            - containerPort: 5000
