apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  selector:
    app: mi-app
    version: blue   # inicialmente blue
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
